version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        container_name: gold_trading_app
        ports:
            - "8000:8000"
            - "9501:9501"
        volumes:
            - .:/var/www/html
            - ./storage/logs:/var/www/html/storage/logs
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=mysql
            - DB_DATABASE=gold_trading
            - DB_USERNAME=root
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - OCTANE_SERVER=swoole
            - OCTANE_HOST=0.0.0.0
            - OCTANE_PORT=8000
            - OCTANE_WORKERS=4
        depends_on:
            - mysql
            - redis
        networks:
            - gold_trading_network
        command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000

    mysql:
        image: mysql:8.0
        container_name: gold_trading_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: gold_trading
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - gold_trading_network

    redis:
        image: redis:7-alpine
        container_name: gold_trading_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - gold_trading_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: gold_trading_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
        depends_on:
            - mysql
        networks:
            - gold_trading_network

    nginx:
        image: nginx:alpine
        container_name: gold_trading_nginx
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - gold_trading_network

volumes:
    mysql_data:
    redis_data:

networks:
    gold_trading_network:
        driver: bridge
